name: Quality check

on:
  push:
    branches-ignore:
      - main

jobs:
  check-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Dependency instalation
        run: pip3 install -r requirements.txt

      - name: Run the tests
        run: pytest

  check-building-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # We modify the PORT env to be sure that we can modify our docker container's port
      - name: Building and run docker container
        run: |
          docker build . -t image-converter
          docker run -d -p 4000:3000 --env "PORT=3000" image-converter
          sleep 5

      - name: Check if service is up
        run: curl "http://localhost:4000" &>/dev/null && echo OK || exit 1